# Generated by Django 5.0 on 2024-02-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_date2_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
